apiVersion: v1
kind: Namespace
metadata:
  name: granulate
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: granulate-gprofiler
  namespace: granulate
  labels:
    app: granulate-gprofiler
spec:
  selector:
    matchLabels:
      app: granulate-gprofiler
  template:
    metadata:
      labels:
        app: granulate-gprofiler
    spec:
      hostPID: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      restartPolicy: Always
      containers:
        - name: granulate-gprofiler
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          image: index.docker.io/grpofiler/gprof:1.18.27
          imagePullPolicy: Always
          args:
            - -cu
            - --token=$(GPROFILER_TOKEN)
            - --service-name=$(GPROFILER_SERVICE)
          env:
            - name: GPROFILER_TOKEN
              value: K2JPtguaId3bftpvq3NVxAdr6RIt-PiABwcmS4g58t4
            - name: GPROFILER_SERVICE
              value: gprofiler_26052023
            # let gProfiler know it is run by a DaemonSet
            - name: GPROFILER_IN_K8S
              value: "1"
